name: find_a_bomb
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  bubble: ^1.2.1
  flutter_inappwebview: ^6.0.0
  stroke_text: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/

  uses-material-design: true
